### ISSUE TITLE
Data Integrity Issue Following Despawn

### ISSUE THREAD

**Issue by PennyMew** [thygrrr/fennECS#23]
Something wacky going on with Entity despawns.

Minimal reproducible example:

```C#
World = new World();
World.Spawn().Add<int>(1); // Spawn E1
World.Spawn().Add<int>(2); // Spawn E2
World.Query<int>().Stream().For((Entity entity, ref int value) => { if (value == 1) entity.Despawn(); }); // Despawn E1
World.Spawn().Add<int>(3); // Spawn E3
World.Query<int>().Stream().For((Entity entity, ref int value) => { if (value == 2) entity.Despawn(); }); // Despawn E2
World.Query<int>().Stream().For((Entity entity, ref int value) =>
{
    // This Runner will not see E3.
    // This Runner will only see E2, for which entity.Alive == false && value == 2.
});
```

Here's the same thing but with a bunch of print statements so we can see what's going on:

<details>

```C#
World = new World();

Console.WriteLine($"Spawn E1");
World.Spawn().Add<int>(1); // I'm using these ints to identify Entities for despawn targets, because Entity objects are invalidated upon structural changes
Console.WriteLine($"Spawn E2");
World.Spawn().Add<int>(2);

Console.WriteLine($"");

Console.WriteLine($"About to debug print all Entities");
Console.WriteLine($"Expected result:"
    + "\n" + "\t" + "E-00000001 is alive and has value 1"
    + "\n" + "\t" + "E-00000002 is alive and has value 2"
);
Console.WriteLine($"Actual result:");
World.Query<int>().Stream().For((Entity entity, ref int value) =>
{
    string entity_id_only = entity.ToString().Substring(0, "E-00000001".Length);
    string alive_or_dead = entity.Alive ? "alive" : "dead";
    Console.WriteLine($"\t{entity_id_only} is {alive_or_dead} and has value {value}");
});

Console.WriteLine($"");

Console.WriteLine($"Despawn E1");
World.Query<int>().Stream().For((Entity entity, ref int value) => { if (value == 1) entity.Despawn(); });

Console.WriteLine($"");

Console.WriteLine($"About to debug print all Entities");
Console.WriteLine($"Expected result:"
    + "\n" + "\t" + "E-00000002 is alive and has value 2"
);
Console.WriteLine($"Actual result:");
World.Query<int>().Stream().For((Entity entity, ref int value) =>
{
    string entity_id_only = entity.ToString().Substring(0, "E-00000001".Length);
    string alive_or_dead = entity.Alive ? "alive" : "dead";
    Console.WriteLine($"\t{entity_id_only} is {alive_or_dead} and has value {value}");
});

Console.WriteLine($"");

Console.WriteLine($"Spawn E3");
World.Spawn().Add<int>(3);

Console.WriteLine($"");

Console.WriteLine($"About to debug print all Entities");
Console.WriteLine($"Expected result:"
    + "\n" + "\t" + "E-00000002 is alive and has value 2"
    + "\n" + "\t" + "E-00000003 is alive and has value 3"
);
Console.WriteLine($"Actual result:");
World.Query<int>().Stream().For((Entity entity, ref int value) =>
{
    string entity_id_only = entity.ToString().Substring(0, "E-00000001".Length);
    string alive_or_dead = entity.Alive ? "alive" : "dead";
    Console.WriteLine($"\t{entity_id_only} is {alive_or_dead} and has value {value}");
});

Console.WriteLine($"");

Console.WriteLine($"Despawn E2"); // Appears to be the step that causes unexpected behavior
World.Query<int>().Stream().For((Entity entity, ref int value) => { if (value == 2) entity.Despawn(); });

Console.WriteLine($"");

Console.WriteLine($"About to debug print all Entities");
Console.WriteLine($"Expected result:"
    + "\n" + "\t" + "E-00000003 is alive and has value 3"
);
Console.WriteLine($"Actual result:");
World.Query<int>().Stream().For((Entity entity, ref int value) =>
{
    string entity_id_only = entity.ToString().Substring(0, "E-00000001".Length);
    string alive_or_dead = entity.Alive ? "alive" : "dead";
    Console.WriteLine($"\t{entity_id_only} is {alive_or_dead} and has value {value}");
});
```

</details>

Output:

<details>

```
Spawn E1
Spawn E2

About to debug print all Entities
Expected result:
	E-00000001 is alive and has value 1
	E-00000002 is alive and has value 2
Actual result:
	E-00000001 is alive and has value 1
	E-00000002 is alive and has value 2

Despawn E1

About to debug print all Entities
Expected result:
	E-00000002 is alive and has value 2
Actual result:
	E-00000002 is alive and has value 2

Spawn E3

About to debug print all Entities
Expected result:
	E-00000002 is alive and has value 2
	E-00000003 is alive and has value 3
Actual result:
	E-00000002 is alive and has value 2
	E-00000003 is alive and has value 3

Despawn E2

About to debug print all Entities
Expected result:
	E-00000003 is alive and has value 3
Actual result:
	E-00000002 is dead and has value 2
```
</details>

Update: to demonstrate the problem, the final Runner (after despawning E3) can actually be replaced with this:

```C#
foreach (Entity entity in World)
{
    string entity_id_only = entity.ToString().Substring(0, "E-00000001".Length);
    string alive_or_dead = entity.Alive ? "alive" : "dead";
    int value = (entity.Alive && entity.Has<int>()) ? entity.Ref<int>() : -999999; // Sentinel value. If entity is dead, .Ref causes exception.
    Console.WriteLine($"\t{entity_id_only} is {alive_or_dead} and has value {value}");
}
```

which still demonstrates the unexpected behavior. I wonder if this might suggest that the issue is related to data integrity of the World/Archetypes rather than an issue with the Query.

Another Update:

Here's another example of an issue, probably the same one, where something appears to be very wrong with the data integrity following a despawn.

<details>

```C#
World = new World();

World.Spawn().Add<int>(1); // Spawn E1
World.Spawn().Add<int>(2); // Spawn E2
World.Query<int>().Stream().For((Entity entity, ref int value) => { if (value == 1) entity.Despawn(); }); // Despawn E1
World.Spawn().Add<int>(3); // Spawn E3
World.Spawn().Add<int>(4); // Spawn E4
World.Spawn().Add<int>(5); // Spawn E5
World.Query<int>().Stream().For((Entity entity, ref int value) => { if (value == 3) entity.Despawn(); }); // Despawn E3

// Expected result:
//     E-00000002 is alive and has value 2
//     E-00000004 is alive and has value 4
//     E-00000005 is alive and has value 5

foreach (Entity entity in World)
{
    string entity_id_only = entity.ToString().Substring(0, "E-00000001".Length);
    string alive_or_dead = entity.Alive ? "alive" : "dead";
    string value;
    try { value = entity.Ref<int>().ToString(); } // throws if Entity dead or if Entity's index is messed up
    catch (Exception e) { value = e.ToString(); }
    Console.WriteLine($"\t{entity_id_only} is {alive_or_dead} and has value {value}");
}

// Actual result:
// 	E-00000002 is alive and has value 5
// 	E-00000005 is alive and has value System.IndexOutOfRangeException: Index was outside the bounds of the array.
// 		at fennecs.World.GetComponent[T](Identity identity, Match match) in D:\git\fennecs\fennecs\World.CRUD.cs:line 86
// 		at fennecs.Entity.Ref[C]() in D:\git\fennecs\fennecs\Entity.cs:line 79
// 		at {Penny's code here}
// 	E-00000004 is alive and has value 4

// Entity 2 has entity 5's data!!!
```

</details>

I'm trying to look through fennecs to understand why this is happening, but it's my first time looking at fennecs and I'm not familiar with the architecture at all. I noticed that World's DespawnImpl calls Archetype Delete, but I don't see anywhere that calls PatchMeta following despawn. Is it true that the Meta Row is used to find an Entity's Component data in an Archetype's Storages? If the Storages delete an element, wouldn't we need to update the Rows for affected Metas of Entities in that Archetype?

**Comment by PennyMew** [comment]
I might have fixed it? See https://github.com/outfox/fennecs/pull/24
